name: Create Git Tag
 
on:
  push:
    branches:
      - master
 
jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
      - uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: push tag
      - uses: actions/checkout@v2
      - run: |
          echo ${{ steps.tag_version.outputs.new_tag }} > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
