name: Create Git Tag

on:
  push:
    branches:
      - release-test

jobs:
  create-git-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "minor"
      - name: Tag push
        run: |
          echo ${{ steps.tag_version.outputs.new_tag }} > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
