name: Create Git Tag

on:
  push:
    branches:
      - release-*

jobs:
  create-git-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ 'patch' }}
          WITH_V: true
          INITIAL_VERSION: 0.0.0
